import React, { useId } from "react";

const Input = React.forwardRef(function Input(
  { label, type = "text", placeholder = "", className = "", ...props },
  ref,
) {
  const id = useId();

  return (
    <div className="w-full">
      {label && (
        <label className="block text-md font-semibold text-gray-700 mb-2 ml-1">
          {label}
        </label>
      )}
      <input
        type={type}
        className={`px-3 py-2 rounded-lg bg-white text-black outline-none focus:bg-gray-50 duration-200 border border-gray-300 w-full ${className}`}
        ref={ref}
        {...props}
        readOnly={label === "Slug"}
        placeholder={(label === "Slug") ? `Autogenerated from title` : `Enter ${label}`}
        id={id}
      />
    </div>
  );
});

export default Input;
